language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.5
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install python-dev python-setuptools python-pip libgraphviz-dev
install:
 - pip install -q argparse --use-mirrors
 - pip install -q -r requirements_test.txt
script:
 - python manage.py test member commission initiatives parliamentarygroup term vote
