language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
install:
 - pip install argparse --use-mirrors
 - pip install -r requirements.txt --use-mirrors
script: python manage.py test member parliamentarygroup term vote
